name: release

on:
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Rust Release binary (linux x86_64)
  # You may pin to the exact commit or the version.
  # uses: rust-build/rust-build.action@7d5b0c135ddb825f7692d4d2d75e598184d15cec
      uses: rust-build/rust-build.action@v1.4.3
      with:
        # Output target
        RUSTTARGET: x86_64-unknown-linux-gnu
        # List of archive types to publish the binaries with, default "zip", supports zip and all tar formats
        ARCHIVE_TYPES: tar.gz, tar.bz
        #   If set to "true", the resulting binary will be stripped and compressed by UPX. ("false" by default)
        MINIFY: false
        # The rust toolchain version to use (see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification)
        TOOLCHAIN_VERSION: stable
        # What method to use to upload compiled binaries, supported values: (release, none), default: release
        UPLOAD_MODE: none
